import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const openSans = localFont({
  src: [
    { path: "../public/fonts/Open_Sans/static/OpenSans-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/Open_Sans/static/OpenSans-Bold.ttf", weight: "700", style: "bold" },
  ],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
